@token = {{ login.response.body.access_token }}

GET http://localhost:3000/users
    ?page=2
    &limit=10
    &sortBy=asc
    &name=sidney
    &age=30
Content-Type: application/json
Authorization: Bearer {{ token }}

###
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "adsfs"
}

###
POST http://localhost:3000/users/create
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "firstName": "Beltrano",
  "lastName": "de Tal",
  "age": 23,
  "email": "test@email.com"
}

###
GET http://localhost:3000/users/b4089103-77bd-4259-baf5-e8f0a1828b41
Content-Type: application/json
Authorization: Bearer {{ token }}
