GET http://localhost:3000/users
    ?page=2
    &limit=10
    &sortBy=asc
    &name=sidney
    &age=30

###
GET http://localhost:3000/users/posts

###
POST http://localhost:3000/users/create
Content-Type: application/json

{
  "firstName": "Beltrano",
  "lastName": "de Tal",
  "age": 23,
  "email": "test@email.com"
}

###
GET http://localhost:3000/users/ba81f515-a8a0-4b3f-86df-f5c641b1b0f1

###
POST http://localhost:3000/users/transform/34
Content-Type: application/json

{
  "username": "test-user",
  "email": "test@email.com"
}